Update calltree helper scripts
- Update for new calltree options
- If destination file is older than source file, re-create it
- If files are already generated, don't check for / complain
  about tools needed to generate them
- More helpful texts after report have been generated

diff --git a/scripts/rtrace-graphs-function b/scripts/rtrace-graphs-function
--- a/scripts/rtrace-graphs-function
+++ b/scripts/rtrace-graphs-function
@@ -24,12 +24,26 @@
 # Originally this file was a part of libleaks package, but moved
 # to the sp-rtrace package during libleaks redesign.
 #
+#
+# CHANGES
+#
+# 2010-08-02
+# - Updated to support rtrace format and moved to sp-rtrace pacakge.
+# 2010-09-10
+# - Update help and calltree options
+# - If destination file is older than source file, re-create it
+# - If files are already generated, don't check for / complain
+#  about tools needed to generate them
+#
+# Originally this file was a part of sp-libleaks package, but moved
+# to the sp-rtrace package during libleaks redesign.
 
 # check command line args
 if [ $# -lt 3 ]; then
 	echo "Generates graphs of unfreed resource allocations going"
-	echo "through given function for all given trace files.  The graphs"
-	echo "are saved to a subdirectory with the given function name."
+	echo "through given functions matching given function name prefix"
+	echo "in all given trace files. The graphs are saved to"
+	echo "a subdirectory with the given function name (prefix)."
 	echo
 	echo "Good values for <limit> are 0.1 - 2, depending on the trace"
 	echo "file contents."
@@ -40,43 +54,52 @@ if [ $# -lt 3 ]; then
 	exit 1
 fi
 
+# if path given for script, make sure rest of things can be
+# executed from that path too (helps testing it)
+if [ \! -z "${0%/*}" ]; then
+	export PATH=$PATH:${0%/*}
+fi
+
 fun=$1
 limit=$2
 shift
 shift
 
 # check for required utilities
-if [ -z $(which sp-rtrace-resolve) ]; then
-	echo "ERROR: 'sp-rtrace-resolve' utility missing from PATH"
-	exit 1
-fi
-if [ -z $(which sp-rtrace-postproc) ]; then
-	echo "ERROR: 'sp-rtrace-postproc' utility missing from PATH"
-	exit 1
-fi
-if [ -z $(which rtrace-calltree) ]; then
-	echo "ERROR: 'rtrace-calltree' utility missing from PATH"
-	exit 1
-fi
-if [ -z $(which dot) ]; then
-	echo "ERROR: 'dot' utility is missing from PATH"
-	echo "- 'dot' it used for converting the graphs into PostScript"
-	echo "- you can get it from http://www.graphviz.org/"
-	echo "  (configure GraphViz with '--without-x')"
-	exit 1
-fi
+function check_resolve
+{
+	if [ -z $(which sp-rtrace-resolve) ]; then
+		echo "ERROR: 'sp-rtrace-resolve' utility missing from PATH"
+		exit 1
+	fi
+	if [ -z $(which sp-rtrace-postproc) ]; then
+		echo "ERROR: 'sp-rtrace-postproc' utility missing from PATH"
+		exit 1
+	fi
+}
+function check_calltree
+{
+	if [ -z $(which rtrace-calltree) ]; then
+		echo "ERROR: 'rtrace-calltree' utility missing from PATH"
+		exit 1
+	fi
+}
+function check_dot
+{
+	if [ -z $(which dot) ]; then
+		echo "ERROR: 'dot' utility is missing from PATH"
+		echo "- 'dot' it used for converting the graphs into PostScript"
+		echo "- you can get it from http://www.graphviz.org/"
+		echo "  (configure GraphViz with '--without-x')"
+		exit 1
+	fi
+}
 
-
-if [ -d $fun ]; then
-	echo "ERROR: directory '$fun' exists already,"
-	echo "cowardly refusing to overwrite it."
-	exit 1
-else
-	mkdir $fun
-fi
+mkdir -p $fun
 
 # process all given trace files
 echo "-------------------------------------------------------------------"
+count=0
 for trace in $*
 do
 	echo "Processing '$trace'..."
@@ -85,21 +108,23 @@ do
 		exit 1
 	fi
 	resolved=${trace%.txt}.resolved
-	if [ \! -f $resolved ]; then
+	if [ \! -f $resolved ] || [ $resolved -ot $trace ]; then
+		check_resolve
 		echo "Removing freed allocations and resolving traces: $trace -> $resolved"
 		sp-rtrace-postproc -lcri $trace > $resolved
 		if [ $? != 0 ]; then
 			rm $resolved
-			echo "ERROR: 'sp-rtrace-resolve' call failed"
+			echo "ERROR: 'sp-rtrace-postproc/-resolve' call failed"
 			exit 1
 		fi
 	fi
 	dot=$fun/${resolved%.resolved}.dot
-	if [ \! -f $dot ]; then
+	if [ \! -f $dot ] || [ $dot -ot $resolved ]; then
+		check_calltree
 		echo "Generating call tree: $resolved -> $dot"
 		rtrace-calltree --type=graph --limit=$limit --emph-limit=4 \
-		--include-only=$fun --ignore=malloc --ignore=realloc \
-		--ignore=strdup --ignore=memdup $resolved > $dot
+		--include-only=$fun --trace-args=yes --ignore-libc-allocs=yes \
+		$resolved > $dot
 		if [ $? != 0 ]; then
 			rm $dot
 			echo "ERROR: 'rtrace-calltree' call failed"
@@ -107,7 +132,8 @@ do
 		fi
 	fi
 	ps=${dot%.dot}.ps
-	if [ \! -f $ps ]; then
+	if [ \! -f $ps ] || [ $ps -ot $dot ]; then
+		check_dot
 		echo "Plotting function call graph: $dot -> $ps"
 		dot -Tps $dot > $ps
 		if [ $? != 0 ]; then
@@ -115,16 +141,22 @@ do
 			echo "ERROR: 'dot' (GraphViz) call failed"
 			exit 1
 		fi
+		count=$((count+1))
 	fi
 done
+
+if [ $count -eq 0 ]; then
+	echo "NOTE: All .rtrace.txt, .resolved or .dot files already processed."
+	echo
+fi
 
 echo "-------------------------------------------------------------------"
 echo
 echo "Generated graphs of allocations going through function '$fun'"
 echo "and showing nodes for functions through which went at least $limit%"
-echo "those allocations."
+echo "of those allocations."
 echo
 echo $fun/
-ls $fun/
+ls $fun/*.ps $fun/*.dot|sed 's/^/- /'
 echo
 echo "DONE!"
diff --git a/scripts/rtrace-graphs-overview b/scripts/rtrace-graphs-overview
--- a/scripts/rtrace-graphs-overview
+++ b/scripts/rtrace-graphs-overview
@@ -32,32 +32,53 @@
 # - parse both alloc leaks and unreffed Gobject reports
 # 2010-08-02
 # - Updated to support rtrace format and moved to sp-rtrace pacakge.
+# 2010-09-10
+# - Add help and update calltree options
+# - If destination file is older than source file, re-create it
+# - If files are already generated, don't check for / complain
+#  about tools needed to generate them
 #
-# Originally this file was a part of libleaks package, but moved
+# Originally this file was a part of sp-libleaks package, but moved
 # to the sp-rtrace package during libleaks redesign.
-#
 
 
 count=0
 
-if [ -z $(which sp-rtrace-resolve) ]; then
-	echo "EROR: 'sp-rtrace-resolve' utility missing from PATH"
-	exit 1
-fi
-if [ -z $(which sp-rtrace-postproc) ]; then
-	echo "EROR: 'sp-rtrace-postproc' utility missing from PATH"
+if [ $# -gt 0 ]; then
+	echo "usage: ${0##*/}"
+	echo
+	echo "Resolves all *.rtrace.txt files in current directory"
+	echo "(unless corresponding *.rtrace.txt.resolved files exist)"
+	echo "and generates overview callgraphs out of them using"
+	echo "rtrace-calltree, python and GraphViz."
 	exit 1
 fi
 
+# if path given for script, make sure rest of things can be
+# executed from that path too (helps testing it)
+if [ \! -z "${0%/*}" ]; then
+	export PATH=$PATH:${0%/*}
+fi
 
-# resolve function names all trace files
-echo "Resolving all unresolved .trace leak files..."
+# -------------------------------------------------------------------
+# resolve function names in all trace files
+echo "Resolving all unresolved addresses in resource trace files..."
 for trace in *.rtrace.txt
 do
 	resolved=${trace%.txt}.resolved
-	if [ -f $resolved ]; then
+	if [ -f $resolved ] && [ $resolved -nt $trace ]; then
 		continue
 	fi
+
+	if [ -z $(which sp-rtrace-resolve) ]; then
+		echo "ERROR: 'sp-rtrace-resolve' utility missing from PATH"
+		exit 1
+	fi
+	if [ -z $(which sp-rtrace-postproc) ]; then
+		echo "ERROR: 'sp-rtrace-postproc' utility missing from PATH"
+		exit 1
+	fi
+
 	echo "Removing freed allocations and resolving traces: $trace -> $resolved"
 	sp-rtrace-postproc -lcri $trace > $resolved
 	if [ $? != 0 ]; then
@@ -68,21 +89,24 @@ do
 	count=$(($count+1))
 done
 
+# -------------------------------------------------------------------
 # generate dot files for all resolved traces
-echo "Generating overview .dot files for all .resolved leak files..."
+echo "Generating overview .dot files of non-freed resource allocations..."
 for resolved in *.rtrace.resolved
 do
 	dot=${resolved%.resolved}.dot
-	if [ -f $dot ]; then
+	if [ -f $dot ] && [ $dot -nt $resolved ]; then
 		continue
 	fi
 	if [ -z $(which rtrace-calltree) ]; then
 		echo "ERROR: 'rtrace-calltree' utility missing from PATH"
 		exit 1
 	fi
+
 	echo "Generating call tree: $resolved -> $dot"
 	rtrace-calltree --type=graph --limit=1 --emph-limit=5 \
-	--ignore-gtk-internals=yes --show-below-limit=no $resolved > $dot
+	--ignore-libc-allocs=yes --ignore-glib-internals=yes --ignore-qt-internals=yes \
+	--trace-args=yes --show-below-limit=no $resolved > $dot
 	if [ $? != 0 ]; then
 		rm $dot
 		echo "ERROR: 'rtrace-calltree' call failed"
@@ -91,23 +115,26 @@ do
 	count=$(($count+1))
 done
 
-if [ -z $(which dot) ]; then
-	echo "ERROR: 'dot' utility is missing from PATH"
-	echo "- 'dot' it used for converting the graphs into PostScript"
-	echo "- you can get it from http://www.graphviz.org/"
-	echo "  (configure GraphViz with '--without-x')"
-	exit 1
-fi
-
+# -------------------------------------------------------------------
 # generate postscript files of all dot files
-echo "Converting .dot files to .ps PostScript files..."
+dotted=0
+echo "Converting allocation graph to PostScript files..."
 for dot in *.rtrace.dot
 do
 	ps=${dot%.dot}.ps
-	if [ -f $ps ]; then
+	if [ -f $ps ] && [ $ps -nt $dot ]; then
+		dotted=$((dotted+1))
 		continue
 	fi
-	echo "Plotting function call graph: $dot -> $ps"
+	if [ -z $(which dot) ]; then
+		echo "ERROR: 'dot' utility is missing from PATH"
+		echo "- 'dot' it used for converting the graphs into PostScript"
+		echo "- you can get it from http://www.graphviz.org/"
+		echo "  (configure GraphViz with '--without-x')"
+		exit 1
+	fi
+
+	echo "converting function call graphs: $dot -> $ps"
 	dot -Tps $dot > $ps
 	if [ $? != 0 ]; then
 		rm $ps
@@ -118,11 +145,21 @@ do
 done
 
 if [ $count -eq 0 ]; then
-	echo "WARNING: No .trace, .resolved or .dot files to process."
+	if [ $dotted -eq 0 ]; then
+		echo "WARNING: No .rtrace.txt, .resolved or .dot files to process."
+	else
+		echo "All .rtrace.txt, .resolved or .dot files already processed. Remove files to re-created them:"
+		ls *.rtrace.txt *.rtrace.resolved *.rtrace.dot *.rtrace.ps
+	fi
 	exit 1
 fi
 
 echo
-ls *.ps
+echo "REPORTS:"
+ls *.ps|sed 's/^/- /'
 echo
 echo "DONE!"
+echo
+echo "Please use the 'rtrace-graphs-function' script to get more detailed"
+echo "callgraphs about things done through specific functions for:"
+ls *.rtrace.txt|sed 's/^/- /'
